product_index:
    path:     /list/{category}
    defaults: { _controller: "AppBundle:Product:index", category: tous }
    methods:  GET

product_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Product:show" }
    methods:  GET

product_new:
    path:     /new
    defaults: { _controller: "AppBundle:Product:new" }
    methods:  [GET, POST]

product_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Product:edit" }
    methods:  [GET, POST]

product_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Product:delete" }
    methods:  DELETE

#    delete ajax
product_remove:
    path:     /{id}/remove
    defaults: { _controller: "AppBundle:Product:remove" }