<?php

namespace Core2Bundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function  ListeProduitParCatgorie()
    {
        $qb = $this->createQueryBuilder('c');
        
        $qb->select()
                ->leftJoin('c.produit', 'p'); 
        return $qb->getQuery()->getResult();
    }
}
